[connect] Improve synopsis, get rid of environment variables

diff --git a/connect b/connect
--- a/connect
+++ b/connect
@@ -1,22 +1,42 @@
 #!/bin/sh
-# Connect to remote ${host} through ssh(1) or mosh(1) depending on the
-# current network connectivity and execute given command.
-# Hosts defined in ssh_config(5) are used, thus only the ${host} and
-# optional ${mosh_ports} must be provided through the environment.
-# IPv6 is always preferred over IPv4 unless ssh_config(5) overwrites
-# this behaviour.
+# Connect to remote host through ssh(1) or mosh(1) depending on the
+# current network connectivity execute given command.
+# Wrapper to connect to remote hosts defined in ssh_config(5)
+# transparently through ssh(1) or mosh(1) depending on network
+# connectivity. IPv6 is always preferred over IPv4, Tor hidden services
+# can be used as last resort.
 #
-# Usage:	$ env HOST=foo MOSH_PORTS=61000:62000 connect \
-#			tmux a -t <session-name>
-# Example ssh_config(5) for ${host}-tor, see nc(1) for more information
+# Example ssh_config(5) for host foo over Tor:
 #
-# Host foo-tor
-#	Hostname	0xdeadbeef123456.onion
-#	ProxyCommand	nc -6nX5 -x[::1]:9050 %h %p
+#	Host foo-tor
+#		Hostname	0xdeadbeef123456.onion
+#		ProxyCommand	nc -6nX5 -x[::1]:9050 %h %p
 
-host="${HOST:?hostname must not be empty}"
-mosh_ports="${MOSH_PORTS:-60000:61000}"
-remote_cmd="${@:?remote command must not be empty}"
+err() {
+	cat <<- EOF 1>&2
+		${1:-}
+		usage: ${0##*/} <host> [-p <mosh_port>[:<mosh_port2>]]
+		       [cmd [args...]]
+		EOF
+	exit 1
+}
+
+[ -n "${host:=${1}}" ] ||
+	err 'hostname missing'
+shift 1
+case "${1}" in
+-p)
+	case "${2}" in
+	[0-9]*|[0-9]*:[0-9]*)
+		mosh_ports="-p ${2}"
+		;;
+	*)
+		err 'invalid mosh port'
+	esac
+	shift 2
+	;;
+esac
+remote_cmd="${@:-}"
 ssh_opts='-oStrictHostKeyChecking=no -oUserKnownHostsFile=/dev/null'
 
 ip() {
@@ -28,15 +48,15 @@ ip() {
 
 mosh() {
 	set -x
-	command mosh --family=prefer-inet6 ${1:-} \
+	command mosh --family=prefer-inet6 ${mosh_ports:-} \
 		--ssh="ssh -oConnectTimeout=5 ${NO_CHECK:+${ssh_opts}}" \
-		-- "${2:-${host}}" ${remote_cmd}
+		-- "${1:-${host}}" ${remote_cmd:-}
 }
 
 ssh() {
-	s	x
-	command ssh -t -oConnectTimeout=5 ${NO_CHECK:+${ssh_opts}} ${1} \
-		-- "${2:-${host}}" ${remote_cmd}
+	set -x
+	command ssh -t -oConnectTimeout=5 ${NO_CHECK:+${ssh_opts}} \
+		-- "${1:-${host}}" ${remote_cmd:-}
 }
 
 printf 'LAN...\n'
@@ -53,10 +73,10 @@ NO_CHECK=1
 for f in 6 4; do
 	ip="$(ip -${f})"
 	printf '  IPv%d: %s\n' ${f} "${ip:-failed}"
-	mosh "-p ${mosh_ports}" "${ip}" ||
-	ssh "${USER}"@"{ip}" ||
+	mosh "${ip}" ||
+	ssh "${ip}" ||
 		printf '  IPv%d failed\n' ${f}
 done
 
-exec command ssh "${host}"-tor ||
+exec command ssh -t "${host}"-tor ||
 	printf 'Tor failed\n'
