[lman] Revamp internals, use man(1) transparently
Instead of using mandoc(1), simply provide $MANPATH (through $LMANPATH)
as native environment for man(1).

That way options do not have to be parsed in lman itself but can be
passed on to man(1).

diff --git a/lman b/lman
--- a/lman
+++ b/lman
@@ -1,8 +1,6 @@
 #!/bin/sh
 # Download Linux manual pages from manpages.debian.org and cache them
-# for transparent offline usage.
-# LMANPATH can be appended to MANPATH to provide "native" fallback.
-# See man(1) and mandoc(1) for options
+# under $LMANPATH, same usage as man(1).
 
 die() {
 	printf '%s: %s\n' "${0##*/}" "${2}" 1>&2
@@ -10,91 +8,84 @@ die() {
 }
 
 usage() {
-	cat << EOF 1>&2
-usage: ${0##*/} [-c] [-O options] [-T output] [-r release] [-p package]
-            [-s section] [-l language] name
-EOF
+	MANPATH= man -h man | sed -e '/^-*$/d' 1>&2
 	exit ${1}
 }
 
+MKDIR() {
+	[ -d "${1}" ] || mkdir -p "${1}" || exit ${?}
+}
+
+curlopts='--connect-timeout 3 -fs'
 
 cache() {
+	MKDIR "${2%/*}"
 	# fetch new/update cached manual page
-	curl --connect-timeout 3 --compressed -fsRz"${2}" -o"${2}" "${1}"
+	curl ${curlopts} --compressed -Rz"${2}" -o"${2}" "${1}"
 }
 
 geturl() {
-	curl -fsLI "${1}" | sed -n s/^Location:\ //p | tr -d \\r |
-		grep -Fv https://dyn.
+	curl ${curlopts} -LI "${1}" | sed -n s,^Location:\ ,,p |
+		tr -d \\r | grep -Fv https://dyn.
 }
 
+# overwrite man(1) search path
+export MANPATH="${LMANPATH:-${HOME}/.lman}"
 
-MKDIR() {
-	[ -d "${1}" ] || mkdir -p "${1}" ||
-		die 1 "${1} cannot be created."
-}
+# offline lookup, save error message
+exec 3>&1
+err=$(man "${@}" 2>&1 1>&3)
+ret=${?}
+exec 3>&-
 
+# quit if some page was read
+[ ${ret} -ne 5 ] && exit ${ret}
 
-args=$(getopt cO:T:r:p:s:l: "${@}") || usage 2
+MKDIR "${MANPATH}"
+
+# parse arguments for required API bits (name, section)
+args=$(getopt acfhklwC:M:m:S:s: "${@}") || usage 5
 set -- ${args}
-
-host=https://manpages.debian.org
-suite=/unstable
-fmt=.gz
-[ -t 0 ] && cflag=-a || cflag=-c
 
 while [ ${#} -ne 0 ]; do
 	case "${1}" in
-	-c)	cflag=-c;	shift;;
-	-O)	Oflag=-O"${2}";	shift 2;;
-	-T)	Tflag=-T"${2}";	shift 2;;
-	-r)	suite=/"${2}";	shift 2;;
-	-p)	pkg=/"${2}";	shift 2;;
-	-s)	section=."${2}";shift 2;;
-	-l)	lang=."${2}";	shift 2;;
-	--)			shift;	break;;
+	-[acfhklw])
+		shift;;
+	-[Ss])
+		eval ${1#-}arg=.${2};
+		shift 2;;
+	-[CMm])
+		printf "'-%s %s' option ignored\n" ${1} "${2}" 1>&2
+		shift 2;;
+	--)
+		shift
+		break;;
 	esac
 done
-
 [ -z "${@}" ] && usage 5
-MANDOC="mandoc ${cflag} ${Oflag} ${Tflag}"
 
 
-lmanpath="${LMANPATH:-${HOME}/.lman}"
-MKDIR "${lmanpath}"
-
-# foo
-name=/"${@}"
+# API parameters
+host=https://manpages.debian.org
+suite=/unstable
+## foo
+name=/"${*}"
+section=${sarg}${Sarg}
+fmt=.gz
 scheme="${host}${suite}${pkg}${name}${section}${lang}${fmt}"
 
 
-# cache lookup
-file=$(find "${lmanpath}" -type f -name "${name#/}${section:-.*}" |
-	grep -E "${name#/}\.[1-9]p?m?$" | head -n1)
-
-# cache hit
-[ -n "${file}" ] && {
-	# update
-	url=$(geturl "${scheme%/*}/${file##*/}${lang}${fmt}")
-	[ -n "${url}" ] && cache "${url}" "${file}"
-	exec ${MANDOC} "${file}"
-}
-
-
-# cache miss
-# https://.../foo.1.en.gz
+## https://.../foo.1.en.gz
 url=$(geturl "${scheme}")
-[ -z "${url}" ] && die 1 "No entry for ${name#/} in the manual."
+[ -z "${url}" ] && die 1 "'${name#/}${section}' could not be found."
 
-# foo.1
+## foo.1
 man=${url##*/} man=${man%.*} man=${man%.*}
 
-lmanpath="${lmanpath}"/man${man##*.}
-MKDIR "${lmanpath}"
+## .../man1/foo.1
+file="${MANPATH}"/man${man#*.}/${man}
 
-# .../man1/foo.1
-file="${lmanpath}"/${man}
-
-# fetch
+## fetch missing page
 cache "${url}" "${file}" || die 1 "Could not fetch ${file}."
-exec ${MANDOC} "${file}"
+
+exec man ${args}
